### PR TITLE
Resolve rework requests

### PR DESCRIPTION
**Pull request by LeoniePhiline**
Resolve some rework requests at https://github.com/djc/askama/pull/700 

# [fix: Remove commented out i18n tests](https://github.com/11Tuvork28/askama/commit/92fadc9bba0c607c48078a7b22d6e64d9da0051c)
Fixes thread https://github.com/djc/askama/pull/700/files#r934558288

# [fix: Add trailing newline to i18n test templates](https://github.com/11Tuvork28/askama/pull/4/commits/98a47777ae340f723e935a24f74eb992b5af9bf7)
Fixes thread https://github.com/djc/askama/pull/700/files#r934508651

# [fix: `cargo fmt`, remove trailing whitespace](https://github.com/11Tuvork28/askama/pull/4/commits/63ed5c93d7f9841bf2d54c45e0cbbec126d155d6)
Fixes CI lint at https://github.com/djc/askama/pull/700/checks

# [fix: Rename feature `localization` to `i18n`](https://github.com/11Tuvork28/askama/pull/4/commits/073e92a7fa1f44d44d6a138cfdb1551a313d389d)
Fixes thread https://github.com/djc/askama/pull/700/files#r934510739

# [opinionated: Rename initialization macro localization! to i18n_load!](https://github.com/11Tuvork28/askama/pull/4/commits/f944c868b366a5d33ff3c43f8482a6164bb1470f)
Rationale: Match module name and [renamed](https://github.com/11Tuvork28/askama/pull/4/commits/073e92a7fa1f44d44d6a138cfdb1551a313d389d) feature name, while still making sense to human readers.

# [style: Change wording "have to" to "need to"](https://github.com/11Tuvork28/askama/pull/4/commits/c32b22d043db92728d6d2d2493fa91d434befe9b)
Improve message wording.

# [refactor: Confine i18n code inside i18n modules](https://github.com/11Tuvork28/askama/pull/4/commits/426575e493faba5eb4ae5d27d6cc2323f86d526d)
You can now [call](https://github.com/11Tuvork28/askama/pull/4/commits/426575e493faba5eb4ae5d27d6cc2323f86d526d#diff-77398b66168add0841bb2b524b937dfb74fa68ae8b685512fd63a25ddb941fadR6)
```rust
askama::i18n::load!(LOCALES);
```
And i18n features no longer leak out of the `i18n` modules.

## [fix: Hide dependency fluent_templates from library users](https://github.com/11Tuvork28/askama/pull/4/commits/81cce1a395c81342aacbab2db687ec3ba6ea57e7)
Just a fix, reverting dependency management to a better state from before the refactor. Library users should not need to add fluent_templates as their crate's dependency.

# [fix(deps): Update dependency fluent-templates to 0.8.0](https://github.com/11Tuvork28/askama/pull/4/commits/1c315d6a34f97cca3c7915fb6833c845f592b6ec)
Update `fluent-templates` to the latest version. The lookup function was changed to return an `Option<String>`.
I chose to `unwrap()` the returned `Option` in the code generator, because the key being looked up (`message`) is checked at compile time.

Dependency changes: https://github.com/XAMPPRocky/fluent-templates/compare/v0.7.1...v0.8.0

# [docs: Add initial i18n module documentation](https://github.com/11Tuvork28/askama/pull/4/commits/6384ae23bfa481e986bf178625f6920b36959bb0)
Adds some initial documentation, based on a test case (simplified).

### CODE REVIEW

**Comment by AndromedaCLI** [comment]
Sick, thanks for helping out^^
Looks good to me so far and the rename of the macro, makes sense to me too!

**Comment by LeoniePhiline** [comment]
I do think renaming the macro makes sense, but I am not sure if `i18n_load!` is the correct name.

Here's my thoughts:

The `_load!` part seems useful to understand the verb of the macro's actions. 

However, I've been pondering about localization vs internationalization; e.g. if the `{{ localize(...) }}` expression should be renamed or not. 

Reading about localization vs internationalization, I found that internationalization is the right name for the _framework_ that _enables localization_. To me this means that it will not make sense to replace all mentions of `localization`, `localize` or `localizer` to variants of `i18n`.

The rationale being: "Internationalization" widens the space or scope to all locales, while "localization" then, as a second step, deliberately reduces the space or scope down to one single desired locale.

I've been considering to call the macro `load_locales!`, but that duplicates "locales" with the passed token (`load_locales!(LOCALES)` -> twice "locales").

What do you think? Is `i18n_load!` a good name? What would be a possible better name, if any?

**Comment by LeoniePhiline** [comment]
I'm ok with merging here. Other changes can be done in a separate PR.

---

Continued discussion:

About https://github.com/djc/askama/pull/700/files#r934508219
What do you think - should this macro be removed, and the macro it `match`es on be called directly? 

This would also solve https://github.com/djc/askama/pull/700/files#r991425622

**Comment by AndromedaCLI** [comment]
Regarding the name `i18n_load!`its fine but I think `load_locales!` is great too but as you already pointed it doubes `locales`. What I thought of is maybe `load_i18n!`. What do you think?

I personally would not rename the expression `{{ localize(...) }}`, once for the reason you already pointed out but also because other libs do this too.

Also removing the macro hm i don't know in my opinion its better to a nice friendly error message there but I think upstream should decide on wether to remove it or not. At least that are my thoughts on it.

I will merge this once I finished eating/ the current episode  :>)

**Comment by LeoniePhiline** [comment]
> What I thought of is maybe `load_i18n!`. What do you think?

I would strongly prefer `i18n_load!`, as the macro in its current form is not namespaced. It is used directly as `askama::...!()`. 
Therefore, mentioning the scope `i18n` before the action `load` reduces mental load when reading the code.

We could also drop the crate-level macro and just rename the (currently misnamed?) `i18n::derive` macro to `load`. 
Library users would then invoke:
```rust
askama::i18n::load!(LOCALES);
```
or:
```rust
use askama::i18n;

i18n::load!(LOCALES);
```
If a user missed enabling the feature then the compiler would inform that the `i18n` module is gated by the `i18n` feature flag.

**Comment by AndromedaCLI** [comment]
Sounds good to me, I more of a "proxy" anyways with this PR.
But yeah I definitely prefer moving it into i18n and renaming the `i18n::derive` function.
In case you wanna read code that uses the i18n [feature](https://github.com/11Tuvork28/rusted-invidious/blob/23-migrate-away-from-the-use-of-_parent-field/src/handlers/home.rs)

**Comment by LeoniePhiline** [comment]
> But yeah I definitely prefer moving it into i18n and renaming the i18n::derive function.

Won't work, unfortunately, due to proc-macro restrictions:
https://stackoverflow.com/questions/56713877/why-do-proc-macros-have-to-be-defined-in-proc-macro-crate

image

**Comment by AndromedaCLI** [comment]
TIL, then lets change it to `i18n_load!` but again thanks for looking into it!

**Comment by LeoniePhiline** [comment]
Fixed it. Check original post for notes for each added commit.

**Comment by LeoniePhiline** [comment]
Added a bit of documentation.

image

**Pull request merged**
